services:
  mysql-server:
    container_name: test-mysql
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    image: mysql:5.7.22
    ports:
    - 3308:3306
    volumes:
    - .:/docker-entrypoint-initdb.d
version: "3"
